# gutterDesk XSETTINGS Daemon Configuration
Net/ThemeName "gutterdesk"
Net/IconThemeName "Papirus-Dark"
Gtk/FontName "Liberation Sans 10"
Gtk/CursorThemeName "DMZ-Black"
Gtk/CursorThemeSize 24
Gtk/ToolbarStyle "Icons"
Gtk/ButtonImages 0
Gtk/MenuImages 1
Gtk/EnableEventSounds 0
Gtk/EnableInputFeedbackSounds 0
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintslight"
Xft/RGBA "rgb"
Xft/DPI 98304
